In [1]:
import numpy as np

In [2]:
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [4]:

# 生成一个简单的测试序列
sequence = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# 调用 split_sequence 函数
n_steps = 3
X, y = split_sequence(sequence, n_steps)

# 打印结果进行调试
print("原始序列:")
print(sequence)
print("\nn_steps:", n_steps)
print("\n输入特征 X (shape: {})".format(X.shape))
print(X)
print("\n目标值 y (shape: {})".format(y.shape))
print(y)

# 详细展示每个样本
print("\n详细对应关系:")
for i in range(len(X)):
    print(f"样本 {i}: 输入 {X[i]} → 目标 {y[i]}")

原始序列:
[ 10  20  30  40  50  60  70  80  90 100]

n_steps: 3

输入特征 X (shape: (7, 3))
[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]
 [70 80 90]]

目标值 y (shape: (7,))
[ 40  50  60  70  80  90 100]

详细对应关系:
样本 0: 输入 [10 20 30] → 目标 40
样本 1: 输入 [20 30 40] → 目标 50
样本 2: 输入 [30 40 50] → 目标 60
样本 3: 输入 [40 50 60] → 目标 70
样本 4: 输入 [50 60 70] → 目标 80
样本 5: 输入 [60 70 80] → 目标 90
样本 6: 输入 [70 80 90] → 目标 100
